//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaDevi.Entities.Concrete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaDeviDBContext : DbContext
    {
        public SinemaDeviDBContext()
            : base("name=SinemaDeviDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<EnteranceLog> EnteranceLogs { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieCast> MovieCasts { get; set; }
        public virtual DbSet<MovieCategory> MovieCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ToDoList> ToDoLists { get; set; }
        public virtual DbSet<Tv> Tvs { get; set; }
        public virtual DbSet<TvCast> TvCasts { get; set; }
        public virtual DbSet<TvSeriesCategory> TvSeriesCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WatchListMovie> WatchListMovies { get; set; }
        public virtual DbSet<WatchListTv> WatchListTvs { get; set; }
    }
}
